### ISSUE TITLE
issue with Go

### ISSUE THREAD

**Issue by w0x68y** [nodauf/GoMapEnum#8]
cmd : 

GoMapEnum owa brute -u 123456 -p 1234567 -t mail.xx.com

Then:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1354431]

goroutine 33 [running]:
GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum.func1(0xc0000b0b40?)
	/Users/gardenvan/Desktop/git/exchange/GoMapEnum/src/orchestrator/userEnum.go:43 +0x1b1
created by GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum
	/Users/gardenvan/Desktop/git/exchange/GoMapEnum/src/orchestrator/userEnum.go:33 +0x297

I'm using go version go1.20.4 darwin/amd64, and use last commit

**Comment by nodauf** [comment]
Thank you for the issue. Do you encounter the error each time your run this command  ?
On my side, I am not able to reproduce the issue with the command you put. 
![image](https://github.com/nodauf/GoMapEnum/assets/7670696/a5ccf809-13d5-4564-844b-b7e53db4e240)

**Comment by w0x68y** [comment]
> Thank you for the issue. Do you encounter the error each time your run this command ? On my side, I am not able to reproduce the issue with the command you put. ![image](https://user-images.githubusercontent.com/7670696/241736725-a5ccf809-13d5-4564-844b-b7e53db4e240.png)

Yes,This error occurs when using a website that can be accessed normally.

**Comment by nodauf** [comment]
The issue should be fixed with the last commit.

**Comment by w0x68y** [comment]
After verifying the user name, an error will be reported when entering the password cracking module:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1353836]

goroutine 454 [running]:
GoMapEnum/src/orchestrator.(*Orchestrator).Bruteforce.func1(0x1ec9acdb4162d3f2?)
	/Users/gardenvan/Desktop/git/exchange/GoMapEnum/src/orchestrator/brute.go:84 +0x536
created by GoMapEnum/src/orchestrator.(*Orchestrator).Bruteforce
	/Users/gardenvan/Desktop/git/exchange/GoMapEnum/src/orchestrator/brute.go:59 +0x585

**Comment by w0x68y** [comment]
You can change CheckIfValid to false, and then blast the account password,which can trigger an error report,like:
GoMapEnum owa brute -u administrator -p 123 -t mail.yuexiu.com
<img width="1457" alt="image" src="https://github.com/nodauf/GoMapEnum/assets/22195911/12502fe3-084c-495b-ab73-d1b91683623c">

**Comment by nodauf** [comment]
Thank you for the bug, it appears than the owa module was only partially updated when the code base was changed. For information, you can change the `-c`  without `-c=false`.
