### ISSUE TITLE
[Kerberos] submodule "userenum" error when valid user is found.

### ISSUE THREAD

**Issue by s7x** [nodauf/GoMapEnum#9]
Hi there,

There's an error when the "userenum" submodule of "kerberos" is ran and finding a valid user:

![image](https://github.com/nodauf/GoMapEnum/assets/33422344/533423b3-b2f8-4b0e-ad39-264a2b8d608a)

**Stack trace**:

```
panic: runtime error: index out of range [1] with length 1

goroutine 8 [running]:
GoMapEnum/src/modules/kerberos.handleKerbError({0x55fcb63122e0?, 0xc0003001c0?})
	GoMapEnum/src/modules/kerberos/utils.go:182 +0x354
GoMapEnum/src/modules/kerberos.UserEnum(0xc000094460?, {0xc00002c2c0, 0xc})
	GoMapEnum/src/modules/kerberos/userEnum.go:12 +0x16e
GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum.func1(0x0?)
	GoMapEnum/src/orchestrator/userEnum.go:43 +0x1ce
created by GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum
	GoMapEnum/src/orchestrator/userEnum.go:33 +0x297
```

Cheers!

**Comment by handbye** [comment]
o365 email enum has same issue
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102568928]

goroutine 18 [running]:
GoMapEnum/src/modules/o365.(*Options).enumOffice(0x1029986c0, 0x140001b836b, 0x19, 0x1029986c0)
	/home/runner/work/GoMapEnum/GoMapEnum/src/modules/o365/utils.go:103 +0x8c8
GoMapEnum/src/modules/o365.UserEnum(0x140001191d0, 0x140001b836b, 0x19, 0x140001b8301)
	/home/runner/work/GoMapEnum/GoMapEnum/src/modules/o365/userEnum.go:13 +0xd4
GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum.func1(0x140001223e0, 0x1400010e120, 0x1029986e8, 0x14000136640, 0x140001191d0, 0x140001223d8, 0x1400012e1b0, 0x0)
	/home/runner/work/GoMapEnum/GoMapEnum/src/orchestrator/userEnum.go:34 +0xf4
created by GoMapEnum/src/orchestrator.(*Orchestrator).UserEnum
	/home/runner/work/GoMapEnum/GoMapEnum/src/orchestrator/userEnum.go:25 +0x298
```
